events {
    worker_connections 1024;
}

http {
    # Редирект HTTP → HTTPS
    server {
        listen 80;
        server_name holiday-vibes.vovisim.ru backend.holiday-vibes.vovisim.ru;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;    # ← для верификации домена certbot
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # Фронтенд HTTPS
    server {
        listen 443 ssl;
        server_name holiday-vibes.vovisim.ru;

        ssl_certificate /etc/letsencrypt/live/holiday-vibes.vovisim.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/holiday-vibes.vovisim.ru/privkey.pem;

        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    # Бэкенд HTTPS
    server {
        listen 443 ssl;
        server_name backend.holiday-vibes.vovisim.ru;

        ssl_certificate /etc/letsencrypt/live/holiday-vibes.vovisim.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/holiday-vibes.vovisim.ru/privkey.pem;

        location / {
            proxy_pass http://api:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}