events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name holiday-vibes.vovisim.ru backend.holiday-vibes.vovisim.ru;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 200 'OK';
        }
    }
}