name: Holiday-Vibes Infrastructure deploy workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Infrastructure to prod
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} <<'EOF'
            if [ ! -d "/projects/holiday-vibes/Infrastructure" ]; then
              git clone git@github-infrastructure:HolidayVibes/Infrastructure.git /projects/holiday-vibes/Infrastructure
            else
              cd /projects/holiday-vibes/Infrastructure
              git reset --hard
              git pull origin main
            fi

            cd /projects/holiday-vibes/Infrastructure

            CERT_PATH="/etc/letsencrypt/live/backend.holiday-vibes.vovisim.ru/fullchain.pem"

            if [ ! -f "$CERT_PATH" ]; then
              echo "Сертификат не найден — получаем через certbot"

              docker compose up -d nginx
              docker cp nginx/nginx.init.conf $(docker compose ps -q nginx):/etc/nginx/nginx.conf
              docker compose exec nginx nginx -s reload

              docker compose run --rm certbot certonly --webroot \
                --webroot-path=/var/www/certbot \
                --email your@email.com \
                --agree-tos \
                --no-eff-email \
                -d holiday-vibes.vovisim.ru \
                -d backend.holiday-vibes.vovisim.ru

              echo "Сертификаты получены — переключаемся на SSL конфиг"
            fi

          docker compose up -d --force-recreate
          EOF